In [ ]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [ ]:
df = pd.read_csv("/content/homepricesMV.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
median = df['bedrooms'].median()
print(median)

4.0


In [ ]:
df.bedrooms.fillna(median,inplace = True)
df


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression()

In [ ]:
reg.coef_
#y = m1*area + m2*bedrooms + m3*age + b

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
reg.intercept_

221323.00186540396

In [ ]:
reg.predict(np.array([[3000,3,40]]))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [ ]:
(112.06244194*3000+23388.88007794*3+-3231.71790863*40)+221323.00186540396

498408.251574024

In [ ]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [ ]:
pip install joblib


In [ ]:
import joblib #to save trained models

In [ ]:
joblib.dump(reg,'/content/homepricesmodel') #to save model in a file type

['/content/homepricesmodel']

In [ ]:
model = joblib.load('/content/homepricesmodel') #loading model from saved file

In [ ]:
model.predict([[2500,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [ ]:
model.score(df[['area','bedrooms','age']],df['price'])

0.9550196399325821